[gwrite.idrawv2]
unit = "mm"
document_start = """(document_start)
G21 ; Set Units to Millimeters
G17 ; Set Plane Selection to XY
G90 ; Set Absolute Positioning
F5000  ; Set Speed to 2500 mm/min
G00 Z0 ; pen up
G00 X0 Y0 ; go to 0,0
"""
layer_start = """(Start Layer)
"""
line_start = """(line_start)
; nothing we'll pendown after segment first
""""
line_end = """(line_end)
G00 Z0
"""
#a line is composed of segments
#segment_first is the command for the first line of a line
segment_first = """(segment_first)
G00 Z0
G0 X{x:.4f}f Y{y:.4f}
G00 Z5
"""
segment = """(segment)
G01 X{x:.4f} Y{y:.4f}
"""
document_end = """(document_end)
G00 X0.0000 Y0.0000
"""
invert_y = true
