name: Generate one artwork for every commit

on: push

jobs:
  gen-art:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Get hash
      shell: bash
      run: |
        echo "sha_short=$(git rev-parse --short "$GITHUB_SHA")"" >> "$GITHUB_ENV
        
      
    - name: Generate artwork
      run: |
        echo "SHA_SHORT: ${{ env.sha_short }}"
        echo "SHA: "$GITHUB_SHA""

    - name: Save artwork
      run: echo "saving"
